// Code generated by stubgen; DO NOT EDIT.

package testdata

type StubInterface5 struct {
	Method5Res0 error
}

func (s StubInterface5) Method5() error {
	return s.Method5Res0
}

type StubInterface6 struct {
	Method6Res0 error
}

func (s StubInterface6) Method6(_ error) error {
	return s.Method6Res0
}
