// Code generated by stubgen; DO NOT EDIT.

package testdata

import (
	"github.com/Gamazic/stubgen/testdata/internal"
)

type StubInterface7 struct {
	Method7Res0 error
}

func (s StubInterface7) Method7() error {
	return s.Method7Res0
}

type StubInterface8 struct {
	M1Res0 error
	M2Res0 bool
	M2Res1 error
	M3Res0 internal.Error
}

func (s StubInterface8) M1(_ int, _ bool) error {
	return s.M1Res0
}

func (s StubInterface8) M2(arg1 int, arg2 bool) (ok bool, err error) {
	return s.M2Res0, s.M2Res1
}

func (s StubInterface8) M3(arg1, arg2 string) internal.Error {
	return s.M3Res0
}

func (s StubInterface8) Empty() {
	return
}
