// Code generated by stubgen; DO NOT EDIT.

package testdata

import (
	"github.com/Gamazic/stubgen/testdata/internal"
)

type StubMyInterface struct {
	AnotherFuncRes0 error
}

func (s StubMyInterface) AnotherFunc(_ int, _ internal.MyStruct) error {
	return s.AnotherFuncRes0
}
