// Code generated by stubgen; DO NOT EDIT.

package testdata

import (
	e "github.com/Gamazic/stubgen/testdata/internal"
)

type StubInterface9 struct {
	Method9Res0 e.Name
}

func (s StubInterface9) Method9() e.Name {
	return s.Method9Res0
}
